In [ ]:
#pandas

**Pandas **

pandas is widely used open source python lybrary that is used for data manipulation and analysis.

it provides tools to work with structured data and especially useful for tasks like data cleaning, exploration and preprocessing

1. data handling:

2. flexible for data formats

3. time effeciently

4. large datasets

5. powerful analysis tool

6. custmizable and scalable work for small scale data analysis as well as large scales,complex data

**series and dataframe**

In [ ]:
# series : a series is like single column of data

# it is list with lables

# it is one dimensinal data and can hold any type of data(numr,text etc)

#features

#data : the actual value

#index : label for each value

In [ ]:
import pandas as pd
number = pd.Series([10,20,30,40],index=['A','B','C','D'])
print(number)

A    10
B    20
C    30
D    40
dtype: int64

In [ ]:
marks = pd.Series([50,49,67,45,89,90]) #st marks
marks

0    50
1    49
2    67
3    45
4    89
5    90
dtype: int64

In [ ]:
#st name
name = pd.Series(['akul','arav','ashish'])
name

0      akul
1      arav
2    ashish
dtype: object

In [ ]:
list = [1,2,3,4,5,6,7,8,9,10]

tuple=(1,2,3,4,5,6,7,8,9,10)

index =['a','b','c','d','e','f','g','h','i','j']

s1 = pd.Series(list,index=index)
print(s1)

s2 = pd.Series(tuple,index=index)
print(s2)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64
a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [ ]:
import pandas as pd
y_set1 = {1,2,3,4,5,6,7,8,9,10}

In [ ]:
# list - yes ,tuple -yes,set -yes

#dict - convert into series

mydict ={'a':10,
         'b':20,
         'c':30,
         'd':40}

print(mydict)

dictseries = pd.Series(mydict)
dictseries

{'a': 10, 'b': 20, 'c': 30, 'd': 40}

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
#create a series using range method

my_series=pd.Series(range(1,11),index=range(1,11))
print(my_series)

1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [ ]:
# Dataframe

# dataframe is like a table

# dataframe is collection of rows and columns

# excel sheet or database table

# features

# it has rows and columns

# u can store diffrent type of data in each column

In [ ]:
data ={
    'Name':['kiran','arsh','arav','ashish'],
    'Age':[20,30,34,36]
}

df = pd.DataFrame(data)
df

     Name  Age
0   kiran   20
1    arsh   30
2    arav   34
3  ashish   36

In [ ]:
data ={
    'Name':['kiran','arsh','arav','ashish'],
    'Age':[20,30,34,36],
    'city':['newyork','america','india','panjab']
}

df = pd.DataFrame(data)
df

     Name  Age     city
0   kiran   20  newyork
1    arsh   30  america
2    arav   34    india
3  ashish   36   panjab

In [ ]:
data =[
    ['arav',20,'america'],
    ['kiran',34,'india'],
    ['ashish',23,'los angles']
]

df = pd.DataFrame(data,columns=['Name','Age','City'])
df

     Name  Age        City
0    arav   20     america
1   kiran   34       india
2  ashish   23  los angles

In [ ]:
df #hide the index
print(df.to_string(index=False))

  Name  Age       City
  arav   20    america
 kiran   34      india
ashish   23 los angles

In [ ]:
data ={
    'Name':['kiran','arsh','arav','ashish'],
    'Age':[20,30,34,36],
    'city':['newyork','america','india','panjab']
}

In [ ]:
import pandas as pd

name_series= pd.Series(['kiran','arsh','arav','ashish'])

age_series = pd.Series([20,30,34,36])

city_series = pd.Series(['newyork','america','india','panjab'])

df = pd.DataFrame({'Name':name_series,'Age':age_series,'City':city_series})
print(df)
print(name_series)
print(age_series)
print(city_series)

     Name  Age     City
0   kiran   20  newyork
1    arsh   30  america
2    arav   34    india
3  ashish   36   panjab
0     kiran
1      arsh
2      arav
3    ashish
dtype: object
0    20
1    30
2    34
3    36
dtype: int64
0    newyork
1    america
2      india
3     panjab
dtype: object

In [ ]:
data = {'st_id':[1,2,3,4,5],
        'st_name':['arav','sujal','ashish','ananya','dev']
}
df = pd.DataFrame(data)
df.style.set_properties(**{
    'background-color':"royalblue",
    'color':"pink",
})

In [ ]:
#accesssing data in pandas

series = pd.Series([10,20,30,40,50],index=[0,1,2,3,4])
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
print(series[3])

40

In [ ]:
print(series[3])

40

In [ ]:
print(series[1:3])

1    20
2    30
dtype: int64

In [ ]:
series[[1,4]]

1    20
4    50
dtype: int64

In [ ]:
series[series>20]

2    30
3    40
4    50
dtype: int64

In [ ]:
series[series<30]

0    10
1    20
dtype: int64

In [ ]:
series[series>20] & series[series<30]

/tmp/ipykernel_2504/3402827413.py:1: FutureWarning: Operation between non boolean Series with different indexes will no longer return a boolean result in a future version. Cast both Series to object type to maintain the prior behavior.
  series[series>20] & series[series<30]

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
# get all values greater than 20 and lesss than 30
series[series>20] | series[series<30]

/tmp/ipykernel_2504/1005061347.py:2: FutureWarning: Operation between non boolean Series with different indexes will no longer return a boolean result in a future version. Cast both Series to object type to maintain the prior behavior.
  series[series>20] | series[series<30]

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [ ]:
a = pd.Series(range(1,20))
a

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64

In [ ]:
# we have to select 12,15,18,19

result = a[a.isin([12,15,18,19])]
result

11    12
14    15
17    18
18    19
dtype: int64

In [ ]:
series

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [ ]:
series +5

A    15
B    25
C    35
D    45
E    55
dtype: int64

In [ ]:
data = {
     'Name':['proma','priya','dev'],
     'Age':[20,23,34],
     'City':['agra','dehli','indor']
 }
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age   City
0  proma   20   agra
1  priya   23  dehli
2    dev   34  indor

In [ ]:
df['Name']

0    proma
1    priya
2      dev
Name: Name, dtype: object

In [ ]:
df['Age']

0    20
1    23
2    34
Name: Age, dtype: int64

In [ ]:
df['City']

0     agra
1    dehli
2    indor
Name: City, dtype: object

In [ ]:
df[0:1] #df[start row : end row]

    Name  Age     City
0  kiran   20  newyork

In [ ]:
df[['Name','Age']]

    Name  Age
0  proma   20
1  priya   23
2    dev   34

In [ ]:
df.loc[:2,['Name','Age']]

    Name  Age
0  proma   20
1  priya   23
2    dev   34

In [ ]:
df[df['Age']>25]

  Name  Age   City
2  dev   34  indor

In [ ]:
# iloc and loc

#rows and columns in a dataframe

# loc : label based indexing

data = {
     'Name':['proma','priya','dev'],
     'Age':[20,23,34],
     'City':['agra','dehli','indor']
 }
df = pd.DataFrame(data)
df

    Name  Age   City
0  proma   20   agra
1  priya   23  dehli
2    dev   34  indor

In [ ]:
print(df.loc[1,'Age'])
print(df.loc[1,'Name'])
print(df.loc[1,'City'])

23
priya
dehli

In [ ]:
df.loc[1: ,['Age','City']] #print age and city of last two rows

   Age   City
1   23  dehli
2   34  indor

In [ ]:
#df.loc[startrow :endrow,[column name,col2,col3]]

In [ ]:
df.loc[1,['Name','City']] #print only priya and dehli

Name    priya
City    dehli
Name: 1, dtype: object

In [ ]:
df[df['City']=='indor']

  Name  Age   City
2  dev   34  indor

In [ ]:
#iloc: integer based indexing

data = {
     'Name':['prem','priya','dev'],
     'Age':[20,26,34],
     'City':['agra','dehli','indor']
 }
df = pd.DataFrame(data)
df

    Name  Age   City
0   prem   20   agra
1  priya   26  dehli
2    dev   34  indor

In [ ]:
#first row and second column
print(df.iloc[1,2])

print(df.loc[0,['Age']])

dehli
Age    20
Name: 0, dtype: object

In [ ]:
print(df.iloc[:2])

    Name  Age   City
0   prem   20   agra
1  priya   23  dehli

In [ ]:
print(df.iloc[0,2]) #index
print(df.loc[0,['City']]) #label

agra
City    agra
Name: 0, dtype: object

In [ ]:
df.iloc[:,1]

0    20
1    23
2    34
Name: Age, dtype: int64

In [ ]:
df.iloc[:,1:]   #select only age and city column using iloc

   Age   City
0   20   agra
1   23  dehli
2   34  indor

In [ ]:
df.iloc[2,2] #select indor

'indor'

In [ ]:
df.loc[2,['City']]

City    indor
Name: 2, dtype: object

In [ ]:
df

    Name  Age   City
0   prem   20   agra
1  priya   23  dehli
2    dev   34  indor

In [ ]:
df.iloc[1:,0:2] # select rows 1 to 2 and column 0 to 1 using iloc

    Name  Age
1  priya   23
2    dev   34

**data selection and filtering in pandas**

In [ ]:
df

    Name  Age   City
0   prem   20   agra
1  priya   23  dehli
2    dev   34  indor

In [ ]:
# select those values where age value >20

df[df['Age']>20]

    Name  Age   City
1  priya   23  dehli
2    dev   34  indor

In [ ]:
# select rows where age >=30 and city is indor

filter_data = df[(df['Age']>=30) & (df['City']=='indor')]
filter_data

  Name  Age   City
2  dev   34  indor

In [ ]:
# select rows where age <30 or city is dehli

filter_data = df[(df['Age']<30) | (df['City']=='dehli')]
filter_data

    Name  Age   City
0   prem   20   agra
1  priya   23  dehli

In [ ]:
df

    Name  Age   City
0   prem   20   agra
1  priya   26  dehli
2    dev   34  indor

In [ ]:
# select tha data where age is less than 30 but more than 25

filter = df[(df['Age']>25) & (df['Age']<30)]
filter

    Name  Age   City
1  priya   26  dehli

In [ ]:
df

    Name  Age   City
0   prem   20   agra
1  priya   26  dehli
2    dev   34  indor

In [ ]:
# select the data where city is not agra
fil = df[df['City']!='agra']
fil

    Name  Age   City
1  priya   26  dehli
2    dev   34  indor

In [ ]:
f = df[~(df['City']=='agra')]
f

    Name  Age   City
1  priya   26  dehli
2    dev   34  indor

In [ ]:
import pandas as pd
data = {
     'Name':['prem','priya','dev'],
     'Age':[20,26,34],
     'City':['agra','dehli','indor']
 }
df5 = pd.DataFrame(data)
df5

    Name  Age   City
0   prem   20   agra
1  priya   26  dehli
2    dev   34  indor

In [ ]:
df5['Salary']=[10000,20000,30000] #adding new column
df5

    Name  Age   City  Salary
0   prem   20   agra   10000
1  priya   26  dehli   20000
2    dev   34  indor   30000

In [ ]:
#updating row
df5.loc[df['Name']=='prem','Salary']=80000
df5

   Name  Age     City   Salary
0  prem   20  newyork  80000.0

In [ ]:
#updating priya age 26 to 40
df.loc[df['Name']=='priya','Age']=40
df

    Name  Age         City
0   prem   20      newyork
1  priya   40  los angeles
2    dev   34      chicago

In [ ]:
# delete prem column
df = df.drop('prem',axis=0)
df

# axes = tells pandas the direction u are working on

# rows axis = 0
# columns axis =1

KeyError: "['prem'] not found in axis"

In [ ]:
df = df.drop(0,axis=0) # delete the 0 row

In [ ]:
df

    Name  Age   City  Salary
1  priya   40  dehli   20000
2    dev   34  indor   30000

In [ ]:
data = {
     'Name':['prem','priya','dev'],
     'Age':[20,26,34],
     'City':['newyork','los angeles','chicago']
 }
df = pd.DataFrame(data)
df

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles
2    dev   34      chicago

In [ ]:
df = df.drop('Name',axis=1)

In [ ]:
df

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles

In [ ]:
df5= df.drop(1,axis=0)
df5

   Name  Age     City
0  prem   20  newyork

In [ ]:
df.drop(2,axis=0 ,inplace=True)

#delete the row 2
# inplace : permanent changes in our data

In [ ]:
df

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles

In [ ]:
data = {
     'Name':['prem','priya','dev'],
     'Age':[20,26,34],
     'City':['newyork','los angeles','chicago']
 }
df = pd.DataFrame(data)
df

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles
2    dev   34      chicago

In [ ]:
df.drop('Name',axis=1,inplace=True)

In [ ]:
#df = df.drop('Name',axis=1)
# we can use also this

In [ ]:
df

   Age         City
0   20      newyork
1   26  los angeles
2   34      chicago

In [ ]:
df = df.drop(['Age','City'],axis=1)
# drop age and city

In [ ]:
df

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles
2    dev   34      chicago

In [ ]:
data = {
     'Name':['prem','priya','dev'],
     'Age':[20,26,34],
     'City':['newyork','los angeles','chicago']
 }
df= pd.DataFrame(data)
df

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles
2    dev   34      chicago

In [ ]:
df.drop(df.index) #delete all index

Empty DataFrame
Columns: [Name, Age, City]
Index: []

In [ ]:
data = {
     'Name':['prem','priya','dev'],
     'Age':[20,26,34],
     'City':['newyork','los angeles','chicago']
 }
df1 = pd.DataFrame(data)
df1

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles
2    dev   34      chicago

In [ ]:
df1.loc[df1['Name'] == 'raj','Age'] = None

In [ ]:
df1

    Name   Age         City
0   prem  20.0      newyork
1  priya  26.0  los angeles
2    dev  34.0      chicago

In [ ]:
df1.loc[df1['Name'] == 'charle','City'] = None

In [ ]:
df1

    Name   Age         City
0   prem  20.0      newyork
1  priya  26.0  los angeles
2    dev  34.0      chicago

In [ ]:
data = {
     'Name':['prem','priya','dev'],
     'Age':[20,26,34],
     'City':['newyork','los angeles','chicago']
 }
df1 = pd.DataFrame(data)
df1

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles
2    dev   34      chicago

In [ ]:
# delete age 26 and city column
df1.loc[df1['Age']==26,'Age'] = None
df1.drop(columns=['City'],inplace=True)
df1

    Name   Age
0   prem  20.0
1  priya   NaN
2    dev  34.0

In [ ]:
data = {
     'Name':['prem','priya','dev'],
     'Age':[20,26,34],
     'City':['newyork','los angeles','chicago']
 }
df1= pd.DataFrame(data)
df1

    Name  Age         City
0   prem   20      newyork
1  priya   26  los angeles
2    dev   34      chicago

In [ ]:
# chenge the name of priya to nidhi
# and delete her age

df1.loc[df1['Name']=='priya','Name'] = 'nidhi'
df1.loc[df1['Age'] == 26,'Age'] = None

In [ ]:
df1

    Name   Age         City
0   prem  20.0      newyork
1  nidhi   NaN  los angeles
2    dev  34.0      chicago

In [ ]:
df1.loc[df1['Name']=='nidhi',['Name','Age']] = ['priya',None]

In [ ]:
df1

    Name   Age         City
0   prem  20.0      newyork
1  priya   NaN  los angeles
2    dev  34.0      chicago

In [ ]:
df1.loc[df1['Name'].isin(['prem','dev']),'Name']=['rohan','nidhi']

In [ ]:
df1

    Name   Age         City
0  rohan  20.0      newyork
1  priya   NaN  los angeles
2  nidhi  34.0      chicago

In [ ]:
df1

    Name   Age         City
0  rohan  20.0      newyork
1  priya   NaN  los angeles
2  nidhi  34.0      chicago

In [ ]:
# add new row
# krish , 30 , new york
df1.loc[3] =['krish',30,'new york']

In [ ]:
df1

    Name   Age         City
0  rohan  20.0      newyork
1  priya   NaN  los angeles
2  nidhi  34.0      chicago
3  krish  30.0     new york

In [ ]:
# between 1 and 2
new_row = pd.DataFrame(
    {
        'Name':['amkit'],
        'Age':[24],
        'City':['dehli']
    }
)
new_row

    Name  Age   City
0  amkit   24  dehli

In [ ]:
df1 = pd.concat([df1.iloc[: 2],new_row, df.iloc[2: ]])
df1

    Name   Age         City
0  rohan  20.0      newyork
1  priya   NaN  los angeles
0  amkit  24.0        dehli
2    dev  34.0      chicago
3  krish  30.0     new york

In [ ]:
df1.reset_index(drop=True)

    Name   Age         City
0  rohan  20.0      newyork
1  priya   NaN  los angeles
2  amkit  24.0        dehli
3    dev  34.0      chicago
4  krish  30.0     new york

In [ ]:
# statitical analysis
df1.describe()

             Age
count   4.000000
mean   27.000000
std     6.218253
min    20.000000
25%    23.000000
50%    27.000000
75%    31.000000
max    34.000000

In [ ]:
df1.head(5)

    Name   Age         City
0  rohan  20.0      newyork
1  priya   NaN  los angeles
0  amkit  24.0        dehli
2    dev  34.0      chicago
3  krish  30.0     new york

In [ ]:
df1.tail()

    Name   Age         City
0  rohan  20.0      newyork
1  priya   NaN  los angeles
0  amkit  24.0        dehli
2    dev  34.0      chicago
3  krish  30.0     new york

In [ ]:
df1.sort_values(by='Age',ascending=True)

    Name   Age         City
0  rohan  20.0      newyork
0  amkit  24.0        dehli
3  krish  30.0     new york
2    dev  34.0      chicago
1  priya   NaN  los angeles

In [ ]:
df1.sort_values(by='Age',ascending=False)

    Name   Age         City
2    dev  34.0      chicago
3  krish  30.0     new york
0  amkit  24.0        dehli
0  rohan  20.0      newyork
1  priya   NaN  los angeles